version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: portfolio_web
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webnet

networks:
  webnet:
